Repository 202306-NEA-DZ-FEW/team-f, pull requests merged in 2023-10, with the labels that each got.

#52 10 category card
  .github/workflows/issue-autolink.yml
  src/components/blogcard/BlogCard.jsx
  src/components/categorycard/CategoryCard.jsx
Labels: Feature Request 🚀

#53 feat(herosection component): add hero section
  public/images/hero-img.svg
  src/components/herosection/HeroSection.jsx
Labels: Feature Request 🚀

#62 6 footer
  public/Logo/logo.png
  src/components/footer/Footer.jsx
  src/layout/Layout.jsx
Labels: Feature Request 🚀, Good First Issue 🌱

#61 Firebase
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/context/AuthContext.js
  src/lib/firebase/firebase.js
  src/lib/firebase/firebaseStorage.js
  src/lib/firebase/firestoreFunctions.js
  src/pages/_app.jsx
Labels: Feature Request 🚀

#48 feat(signupform): add Sign up form component
  src/components/signup/SignUpForm.jsx
Labels: Feature Request 🚀

#60 8 marketing card
  public/marketing-icons/sec1.png
  public/marketing-icons/sec2.png
  public/marketing-icons/sec3.png
  src/components/marketing-card/Card.jsx
  src/components/marketing-card/SectionWithCards.jsx
Labels: Feature Request 🚀

#59 43 avatar developers
  src/components/developeravatar/DeveloperAvatar.jsx
Labels: Feature Request 🚀

#57 38 personal information 1
  public/images/2.png
  src/components/personalinfo/AddItem.jsx
  src/components/personalinfo/PersonalInfo.jsx
Labels: Feature Request 🚀, Good First Issue 🌱

#58 41 blog article card
  src/components/articlecard/ArticleCard.jsx
Labels: Enhancement ✨
